# Configuration file for the analysis of galaxy clustering
statistic: "pk"                # One of ["pk", "bk_sco", "bk_sugi"], Type of statistics to compute    
geometry: "survey-like"          # Geometry of the catalog, either "survey-like" or "box-like"  
catalogs: # if box-like, the randoms catalog will not be used!
  data_path: "/Users/xieyunchen/Downloads/fits_files/DR12_SGC/data/001_galaxy_DR12v5_LOWZ_South.fits" 
  randoms_path: "/Users/xieyunchen/Downloads/fits_files/DR12_SGC/randoms/001_random0_DR12v5_LOWZ_South.fits" 
  # data_path: "/Users/xieyunchen/Downloads/galaxy_DR12v5_CMASS_North.fits" 
  # randoms_path: "/Users/xieyunchen/Downloads/random0_DR12v5_CMASS_North.fits" 
  # data_path: "/Users/xieyunchen/Downloads/galaxy_DR12v5_LOWZ_South.fits" 
  # randoms_path: "/Users/xieyunchen/Downloads/random0_DR12v5_LOWZ_South.fits" 

# order of the column names here is not important, but they must match the real data in the .npy file
# for the .fits file, they are not used.
column_names: ["x", "y", "z","w"] # an example of column names for box-like catalog, "w" is optional
# column_names: ["x", "y", "z","w_comp","w_fkp","nz"] # an example of column names for survey-like catalog


mesh:
  nmesh: [256,256,256]                      # Number of grid points (nx, ny, nz)
  boxsize: [1800,1800,1800]                 # Physical size of the grid (Mpc/h)
  sampler: "tsc"                            # Type of mesh sampling (must be in "tsc", "cic", "pcs")
  interlaced: false                         # Use interlaced mesh sampling

tasks:                                    
  - name: "pk"                            # Task: Power spectrum
    k_min: 0.0                            # Minimum k value (h/Mpc)
    k_max: 0.2                             # Maximum k value (h/Mpc)
    k_bins: 20                             # Number of bins in k-space
    poles: [0,2]                           # Multipole expansion orders
    compensation: true                     # Compensation for the mesh      
    mesh_norm: false                       # Use mesh normalization raised in PyPower, currently not supported
    fast_estimation_mode: closed           # Only in "off","replace","coexist", by default "closed"
                                            # to use the fast estimation, the poles MUST be [0,2,4] otherwise it will be ignored
                                            # Modes of using fast estimation of survey-like geometry based on Legendre expansion only for P4b
                                            # replace: replace the original P4; coexist: coexist with the original P4
    

para_cosmo:                                # for the .npy catalogs and the box like catalogs, the cosmology parameters are not used.
  h: 0.6777                                # Hubble parameter
  Omega0: 0.31377                          # Matter density parameter
  Omega0_b: 0.048                          # Baryon density parameter
  Omega0_cdm: 0.259115                     # CDM density parameter
  n_s: 0.96                                # Scalar spectral index
  sigma8: 0.8288       
                      # Amplitude of matter fluctuations
z_range: [0.15,0.43]                          # Redshift range for the analysis


# the auto mode will automatically search the "WEIGHT" column in the catalog, 
# if not found, it will Added WEIGHT column with default value 1.0.
# the manual mode will firstly check the "WEIGHT" column but in a different name(e.g. name_alias: "weight_no_fkp" )
# if not found, it will firstly check that 'WEIGHT_SYSTOT','WEIGHT_NOZ','WEIGHT_CP' columns are all in the catalog,
# then if the scheme is in "boss" or "eboss", it will give the completeness weight by specific scheme.
comp_weight_plan:
  scheme: "boss"                            # boss or eboss
  name_alias: "sssssss"               # Rename the weight column

output:
  directory: "/Users/xieyunchen/Downloads/res_pk_output"                      # Output directory
